### ISSUE TITLE
Cannot open the links to training data and model

### ISSUE THREAD

**Issue by ChangPtR** [shenyunhang/NA-fWebSOD#10]
The links cannot be open now. So we cannot get your training data and model. Would you please update these links?
![图片](https://user-images.githubusercontent.com/46048008/148214801-d128ac27-23c2-4cec-be52-d5384f737c49.png)
![图片](https://user-images.githubusercontent.com/46048008/148214838-cbb12f1b-dff6-42fb-8293-7aebd8557cbf.png)

**Comment by shenyunhang** [comment]
Sorry for my late response.

It seem the links are till ok.

![image](https://user-images.githubusercontent.com/10623778/160080363-f9145c01-688a-492b-81b5-412db1a4f710.png)
