### ISSUE TITLE
Where is the implementation of bagging mixup?

### ISSUE THREAD

**Issue by ChangPtR** [shenyunhang/NA-fWebSOD#11]
Just cannot find...

**Comment by ChangPtR** [comment]
Well, maybe in loader_wsl.py: get_next_minibatch(self).

**Comment by shenyunhang** [comment]
You are right.
It is in [loader_wsl.py: get_next_minibatch(self)](https://github.com/shenyunhang/NA-fWebSOD/blob/NA-fWebSOD/detectron/roi_data/loader_wsl.py#L130).
