### ISSUE TITLE
Do ground-truth labels mean BN or FL in the sentence? WD and RD have high responses to ground-truth labels and foreground label respectively.

### ISSUE THREAD

**Issue by sisrfeng** [shenyunhang/NA-fWebSOD#3]
Hi, would you mind explaining here a little more in detail?

```
We visualize the proposal scores and pixel gradient
maps of the WD and RD heads in Fig. 4. WD and RD have
high responses to ground-truth labels and foreground labels(FL), 
respectively. The two results combined from WD and
RD can decompose BN from FL.
```
![image](https://user-images.githubusercontent.com/53520949/94551112-6bf52300-0287-11eb-9a14-66c881d93a50.png)
Does decompose mean that if there is a bus and a car in the picture with lable bus, the model will ignore the region containing a car     to make sure the label can match the picture?

Many thx!

**Comment by shenyunhang** [comment]
> Do ground-truth labels mean BN or FL in the sentence?

In fact, ground-truth labels are not BN or FL.

> Hi, would you mind explaining here a little more in detail?

We hope that WD only responses to real ground-truth labels, while RD only response to FL, which may be incorrect.
Meanwhile, RD utilizes the proposal features from WD and RoI-pooled features to fit the potential BN, which imposes models to decompose BN from FL.

> Does decompose mean that if there is a bus and a car in the picture with lable bus, the model will ignore the region containing a car to make sure the label can match the picture?

Yes, your understand is correct.
