### ISSUE TITLE
foreground label means the your query while retrieving images from the Flickr, and background label means the tags provided by Flickr (user or machine) ?

### ISSUE THREAD

**Issue by sisrfeng** [shenyunhang/NA-fWebSOD#4]
![image](https://user-images.githubusercontent.com/53520949/94635923-5a9f2b80-0306-11eb-9bb3-562ee731a852.png)
![image](https://user-images.githubusercontent.com/53520949/94636005-87534300-0306-11eb-846b-30ba4b87732b.png)
![image](https://user-images.githubusercontent.com/53520949/94635993-80c4cb80-0306-11eb-8dd2-844a7e839a47.png)
![image](https://user-images.githubusercontent.com/53520949/94635717-dc428980-0305-11eb-932d-53622f9b3d81.png)

```
If the foreground/background label is true:
    you refer to it as groud truth.
else:
    you refer to it as  foreground/background noise.
```

![image](https://user-images.githubusercontent.com/53520949/94636190-00eb3100-0307-11eb-875f-18b72ef413bc.png)

Noise is mainly from Flickr' s robot.

right?
Thx!

**Comment by shenyunhang** [comment]
> foreground label means the your query while retrieving images from the Flickr, and background label means the tags provided by Flickr (user or machine) ?

When we retrieve images from Flickr, we have a set of pre-defined categories, i.e., 20/80 categories as VOC/COCO.
Given each retrieved image, foreground label is the corresponding query category and the rest 19/79 categories are background labels.

> Noise is mainly from Flickr' s robot. right?

We do not analyze the reasons that cause the noise.
Moreover, we do not glance at the retrieved images to minimize the human effort of making datasets.

**Comment by sisrfeng** [comment]
Thx!
Suppose "nature" is not a VOC category, then in this case, "nature" , which is in the "tags", is neither foreground nor background label, right? 
![image](https://user-images.githubusercontent.com/53520949/96073529-35e7ae00-0ed9-11eb-9dfc-a1601f5ff832.png)
In this schematic diagram, if you want to get VOC format, should BL include car and so on?
![image](https://user-images.githubusercontent.com/53520949/96073756-abec1500-0ed9-11eb-8109-aa6269098ccb.png)

**Comment by shenyunhang** [comment]
> Suppose "nature" is not a VOC category, then in this case, "nature" , which is in the "tags", is neither foreground nor background label, right?

Yes, you are right.
