### ISSUE TITLE
./build_ops.sh  meet some error

### ISSUE THREAD

**Issue by sisrfeng** [shenyunhang/NA-fWebSOD#6]
Hi, would you mind giving me some help on this?
![image](https://user-images.githubusercontent.com/53520949/97068520-c40b1500-15fa-11eb-96e0-44857d99ac35.png)

My command(as root user):
#my path of NA-fWebSOD  is '/opt/data/private/webly'
#pytorch=~/pytorch
git clone https://github.com/pytorch/pytorch.git $pytorch
cd $pytorch
git checkout v1.3.0
git submodule update --init --recursive
pip install -r $pytorch/requirements.txt
cd $pytorch
USE_OPENCV=On USE_LMDB=On BUILD_BINARY=On python3 setup.py install
pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
pip install git+git://github.com/waspinator/pycococreator.git@0.2.0
git clone https://github.com/shenyunhang/NA-fWebSOD.git /opt/data/private/webly
cd /opt/data/private/webly
git submodule update --init --recursive
pip install -r requirements.txt
apt-get install libeigen3-dev
ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
make

**Comment by shenyunhang** [comment]
It seems Detectron can not find Caffe2 library.
Can you build the official [Detectron](https://github.com/facebookresearch/Detectron) repository？
If you can run official [Detectron](https://github.com/facebookresearch/Detectron), it will also be able to build our code.

**Comment by sisrfeng** [comment]
in  build_ops.sh 
`PYTORCH_PATH=~/Documents/pytorch/pytorch`

but my path is :
/root/pytorch

After fixing this line, other errors accur:

![image](https://user-images.githubusercontent.com/53520949/97841703-59a45400-1d21-11eb-8fb3-d1cde125f9af.png)
And at the end:
```
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Did you meet this?

**Comment by shenyunhang** [comment]
I do not meet this before.
It seems that detectron2 can not found the caffe2 head files.
I can find this file in ``/usr/local/lib/python3.8/dist-packages/torch/include/c10/macros/cmake_macros.h``.
You can try to set ```-DCaffe2_DIR``` in build_ops.sh to the right path.
