### ISSUE TITLE
Would you mind showing the visualization results of the code?

### ISSUE THREAD

**Issue by sisrfeng** [shenyunhang/NA-fWebSOD#7]
To compare the results with your baseline, I think visualization results are more straight forward.
![image](https://user-images.githubusercontent.com/53520949/97071294-fd9b4a80-1611-11eb-9ce4-44ccbf71b99a.png)

**Comment by shenyunhang** [comment]
There are several ways to get the visualization results.
You can use the [visualize_results.py](https://github.com/shenyunhang/NA-fWebSOD/blob/NA-fWebSOD/tools/visualize_results.py) scripts.
You can also get the visualization results during training and testing by using [train_net_wsl_vis.py](https://github.com/shenyunhang/NA-fWebSOD/blob/NA-fWebSOD/tools/train_net_wsl_vis.py) and [test_net_wsl_vis.py](https://github.com/shenyunhang/NA-fWebSOD/blob/NA-fWebSOD/tools/test_net_wsl_vis.py) along with configuring options, like cfg.WSL.SAMPLE, cfg.WSL.DEBUG and cfg.VIS.
